### ISSUE TITLE
How to install the package?

### ISSUE THREAD

**Issue by stla** [mlweiss/buchberger_algorithms#2]
Hello,

I read your paper. Very well written. Then I implemented the Gröbner bases in R and I'd like to compare with your implementation. But I don't know how one can install your package?

**Comment by mlweiss** [comment]
Hi, thanks for the question, simply clone the repo and run the code in Python. Let me know if you have any issues.

**Comment by stla** [comment]
Hello,

Which file should I run? All? I started to copy them and my editor (Spyder) indicates that `cmp` is undefined.

**Comment by mlweiss** [comment]
One thing to note is that this is a Python 2 library. You can see some examples of what to run in the doc test in `buchberger.py`

**Comment by stla** [comment]
Ah ok. I don't have Python 2. Anyway I check on Sage online now. 

My package works, the results are correct, but the division of a multivariate polynomial is very slow, even though I implemented it in C++. I'm wondering whether I did something bad.

**Comment by mlweiss** [comment]
You might take a look at the implementation of polynomial division in Sage. Without looking at your package, it would be hard to tell exactly what is causing the slowdown. There can be a lot of pitfalls and nothing obvious comes to mind at the moment.

**Comment by stla** [comment]
Yes I know. Anyway I've done a second package now which allows the computation of Gröbner bases. It is an interface to Giac, the computer algebra system which powers Xcas. Very very efficient.
